yatube/posts/urls.py
from django.urls import path

from . import views

app_name='posts'

urlpatterns = [
    path('', views.index, name ='index'),
    path('group/<slug:slug>/', views.group_posts , name='group_posts'),
    
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('', include('posts.urls', namespace = 'posts')),
    path('admin/', admin.site.urls),
    
]

yatube/posts/models.py
from typing import Text
from django.contrib import auth
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Post(models.Model):
    text = models.TextField()
    pub_date =models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
)
# Create your models here.

yatube/posts/views.py
from typing import Text
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    template = 'posts/index.html'
    title = 'последния обновления сайта'
    text = "это главнаня страница проэкта Yatube"
    context ={
        "text" : text,
        'title': title,
    }
    return render(request, template,context)

def group_posts(request , slug):
    template = 'posts/group_list.html'
    title = 'посты выбраной групы'
    text = "здесь будут информация о групах пректа Yatube"
    context = {
        'text': text,
        'title': title,
        }
    return render(request, template,context)

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% load static %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title> {% block title %}{% endblock %} </title>
  </head>
  <body>
      <header>
        {% include 'includes/header.html' %}

      <header>
    <main> 
      {% block content %}
      {% endblock %}
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      {% include 'includes/footer.html' %}
    </footer>
  </body>

yatube/templates/includes/footer.html
<p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    

yatube/templates/includes/header.html
{% load static %}
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png'%}" width="30" height="30" class="d-inline-block align-top" alt="">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube
        </a>
      </div>
    </nav>      

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{title}}{% endblock %}
{% block content %}{{text}}{% endblock %}
   

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}{{title}}{% endblock %}
{% block content %}{{text}}{% endblock %}